# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hw2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hw2
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NVActivityIndicatorView'

  target 'hw2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hw2UITests' do
    # Pods for testing
  end

end
